name: Publish Preview Update

on:
  pull_request:
    branches: ["dev"]

jobs:
  publish_preview_update:
    name: Publish Preview Update
    type: update
    params:
      branch: ${{ github.ref || 'dev' }}
